package com.stardew.craft.mining;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class MineMonsterSpawnBalanceTest {
    @Test
    void safeFloorsRemainMonsterFree() {
        assertEquals(0, MineGenerationBalance.normalizeMonsterCount(0, 20, false));
        assertEquals(0, MineGenerationBalance.normalizeMonsterCount(1, 20, false));
        assertEquals(0, MineGenerationBalance.normalizeMonsterCount(10, 20, false));
        assertEquals(0, MineGenerationBalance.normalizeMonsterCount(120, 20, true));
    }

    @Test
    void regularMineFloorsHaveAControlledNonZeroPopulation() {
        assertEquals(2, MineGenerationBalance.normalizeMonsterCount(2, 0, false));
        assertEquals(5, MineGenerationBalance.normalizeMonsterCount(37, 5, false));
        assertEquals(8, MineGenerationBalance.normalizeMonsterCount(99, 40, false));
    }

    @Test
    void reusedRegularFloorRepairsAnEmptyPersistedPopulation() {
        assertEquals(2, MineGenerationBalance.expectedReusedFloorPopulation(5, 0));
        assertEquals(7, MineGenerationBalance.expectedReusedFloorPopulation(5, 7));
        assertEquals(0, MineGenerationBalance.expectedReusedFloorPopulation(10, 7));
    }

    @Test
    void generatedPopulationStaysInTheEntranceBand() {
        assertEquals(2, MineGenerationBalance.nearEntranceSpawnTarget(2));
        assertEquals(8, MineGenerationBalance.nearEntranceSpawnTarget(8));
    }

    @Test
    void skullCavernUsesAHigherControlledPopulation() {
        assertEquals(3, MineGenerationBalance.normalizeMonsterCount(121, 0, false));
        assertEquals(7, MineGenerationBalance.normalizeMonsterCount(150, 7, false));
        assertEquals(10, MineGenerationBalance.normalizeMonsterCount(200, 40, false));
    }

    @Test
    void monsterMuskDoublesTheClampedPopulationWithinBoostedCaps() {
        assertEquals(4, MineGenerationBalance.normalizeMonsterCount(2, 0, true));
        assertEquals(12, MineGenerationBalance.normalizeMonsterCount(37, 6, true));
        assertEquals(16, MineGenerationBalance.normalizeMonsterCount(99, 40, true));
        assertEquals(6, MineGenerationBalance.normalizeMonsterCount(121, 0, true));
        assertEquals(20, MineGenerationBalance.normalizeMonsterCount(200, 40, true));
    }

    @Test
    void entranceSpawnRingKeepsMonstersVisibleWithoutUsingTheSafeZone() {
        assertFalse(MineGenerationBalance.isNearEntranceSpawnCandidate(0, 7, 0, 0));
        assertTrue(MineGenerationBalance.isNearEntranceSpawnCandidate(0, 8, 0, 0));
        assertTrue(MineGenerationBalance.isNearEntranceSpawnCandidate(20, 15, 0, 0));
        assertTrue(MineGenerationBalance.isNearEntranceSpawnCandidate(0, 28, 0, 0));
        assertFalse(MineGenerationBalance.isNearEntranceSpawnCandidate(0, 29, 0, 0));
    }

    @Test
    void entranceSpawnBandRejectsHiddenVerticalCaveLayers() {
        assertTrue(MineGenerationBalance.isNearEntranceSpawnCandidate(
                0, 66, 8, 0, 66, 0));
        assertTrue(MineGenerationBalance.isNearEntranceSpawnCandidate(
                12, 62, 0, 0, 66, 0));
        assertFalse(MineGenerationBalance.isNearEntranceSpawnCandidate(
                12, 61, 0, 0, 66, 0));
        assertFalse(MineGenerationBalance.isNearEntranceSpawnCandidate(
                0, 66, 29, 0, 66, 0));
    }

    @Test
    void generatorConfiguresMonstersBeforeSubmittingThemToTheLevel() throws Exception {
        Path project = Path.of(System.getProperty("stardewcraft.projectDir", "."));
        String source = Files.readString(project.resolve(
                "src/main/java/com/stardew/craft/mining/MineFloorGenerator.java"))
                .replaceAll("\\s+", "");

        assertTrue(source.contains("privatestaticfinalintGENERATION_VERSION=26;"),
                "the spawn rebalance must invalidate empty floors generated by the old policy");
        assertTrue(source.contains("nearEntranceSurface"),
                "large floors must reserve nearby candidates so their population is discoverable");
        assertTrue(source.contains("scheduleMonsterSpawnVerification"),
                "accepted entities must be checked after the player reaches the floor");
        assertTrue(countOccurrences(
                        source,
                        "StardewSimulationTaskScheduler.schedule(level,") >= 4,
                "mine monster work must use the real simulation-tick scheduler for every delayed phase");
        assertFalse(source.contains("newnet.minecraft.server.TickTask("),
                "MinecraftServer.tell(TickTask) is not a reliable delayed scheduler on hybrid servers");
        assertTrue(source.contains("scheduleInitialMonsterSpawn"),
                "monster submission must run after the caller teleports the player into the floor");
        assertTrue(source.contains("INITIAL_MONSTER_SPAWN_DELAY_TICKS=40"),
                "hybrid-server entity submission must wait for asynchronous player chunk tracking");
        assertTrue(source.contains("[MINE_DEBUG]population")
                        && source.contains("Config.isServerDebugLoggingEnabled()"),
                "debug mode must expose the final server-side monster positions and visibility state");
        assertTrue(source.contains("getPlayersWatching"),
                "debug mode must expose whether the hybrid server paired each monster to a client");
        assertTrue(source.contains("scheduleReusedFloorMonsterRepair"),
                "re-entering an already-generated floor must repair missing monsters");
        assertTrue(source.contains("hasClearSpawnSpace"),
                "spawn candidates must fit the selected monster's block space");
        assertFalse(source.contains("&&level.noCollision(mob)&&level.addFreshEntity(mob)"),
                "hybrid servers must not hard-reject every pre-join entity when noCollision is unreliable");
        assertTrue(source.contains("replenishMissingMonsters"),
                "hybrid-server removals must receive one bounded population repair");
        assertTrue(source.contains("result.target(),isDark,candidates"),
                "verification must retain the planned target even when the first submission accepts zero mobs");
        assertTrue(source.contains(
                        "MineMonsterSpawnHandler.configureGeneratedMonster(mob,selection.profileId(),floorNumber)"),
                "generated mobs must receive Stardew tags before hybrid-server spawn filters inspect them");
        assertTrue(source.contains("submitGeneratedMonster"),
                "only entities accepted by the level count toward the floor population");
        assertFalse(source.contains("level.addFreshEntity(mob);spawned++;"));
        assertFalse(source.contains("markSelectedProfile(mob,selection)"),
                "profile configuration must not be deferred to EntityJoinLevelEvent");
        assertFalse(source.contains("intmonstersSpawned=spawnMonsters("),
                "floor generation must not submit monsters before teleporting the player");
    }

    @Test
    void generatedMonstersUseYouerCustomSpawnReasonAndAvoidPreJoinCollisionProbe()
            throws Exception {
        Path project = Path.of(System.getProperty("stardewcraft.projectDir", "."));
        String source = Files.readString(project.resolve(
                "src/main/java/com/stardew/craft/mining/MineFloorGenerator.java"))
                .replaceAll("\\s+", "");
        String spawnHandler = Files.readString(project.resolve(
                "src/main/java/com/stardew/craft/event/MineMonsterSpawnHandler.java"))
                .replaceAll("\\s+", "");

        assertTrue(spawnHandler.contains("org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason")
                        && spawnHandler.contains("\"CUSTOM\""),
                "Youer must receive an explicit custom reason for generated mine mobs");
        assertTrue(source.contains("MineMonsterSpawnHandler.addWithSpawnReason"),
                "generated mobs must use the hybrid-aware spawn adapter");
        assertTrue(spawnHandler.contains("youerSpawnBridgeResolved")
                        && spawnHandler.contains("resolveYouerSpawnBridge"),
                "Youer spawn bridge lookup must not run once per monster");
        assertTrue(spawnHandler.contains("mob.getRemovalReason()"),
                "managed monster removals must retain a concise removal reason diagnostic");
        assertFalse(spawnHandler.contains("removalCallStack"),
                "managed monster removals must not capture a reflective call stack per entity");
        assertFalse(spawnHandler.contains("runtimeEntityTtl"),
                "managed monster removal diagnostics must not reflectively inspect entity TTL");
        assertTrue(source.contains("if(!com.stardew.craft.Config.isServerDebugLoggingEnabled())"),
                "spawn diagnostics must be opt-in instead of being emitted for every floor");
        assertFalse(source.contains("level.noCollision(mob)"),
                "Youer's pre-join noCollision result is not a valid spawn gate");
    }

    @Test
    void pepperRexProxyCannotConvertAndDisappearOutsideTheNether() throws Exception {
        Path project = Path.of(System.getProperty("stardewcraft.projectDir", "."));
        String source = Files.readString(project.resolve(
                "src/main/java/com/stardew/craft/event/MineMonsterSpawnHandler.java"))
                .replaceAll("\\s+", "");

        assertTrue(source.contains("sd_mob_dino"),
                "the proxy behavior must be limited to generated Pepper Rex mobs");
        assertTrue(source.contains("setImmuneToZombification(true)"),
                "the Hoglin proxy must not convert into a filtered Zoglin");
    }

    @Test
    void persistentMineMonstersSurviveAWorldUsingPeacefulDifficulty() throws Exception {
        Path project = Path.of(System.getProperty("stardewcraft.projectDir", "."));
        String source = Files.readString(project.resolve(
                "src/main/java/com/stardew/craft/event/MineMonsterSpawnHandler.java"))
                .replaceAll("\\s+", "");

        assertTrue(source.contains("MobDespawnEvent.Result.DENY"),
                "NeoForge's despawn hook must bypass peaceful cleanup for managed mine monsters");
        assertTrue(source.contains("ModMiningDimensions.STARDEW_MINING.equals(mob.level().dimension())"),
                "the peaceful-mode exemption must remain scoped to the mining dimension");
        assertTrue(source.contains("mob.isPersistenceRequired()")
                        && source.contains("tag.startsWith(\"sd_mob_\")"),
                "only persistent managed mine monsters may receive the exemption");
    }

    private static int countOccurrences(String source, String needle) {
        int count = 0;
        int offset = 0;
        while ((offset = source.indexOf(needle, offset)) >= 0) {
            count++;
            offset += needle.length();
        }
        return count;
    }
}
