package com.stardew.craft.mining;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class MineMonsterSpawnBalanceTest {
    @Test
    void safeFloorsRemainMonsterFree() {
        assertEquals(0, MineGenerationBalance.normalizeMonsterCount(0, 20, false));
        assertEquals(0, MineGenerationBalance.normalizeMonsterCount(1, 20, false));
        assertEquals(0, MineGenerationBalance.normalizeMonsterCount(10, 20, false));
        assertEquals(0, MineGenerationBalance.normalizeMonsterCount(120, 20, true));
    }

    @Test
    void regularMineFloorsHaveAControlledNonZeroPopulation() {
        assertEquals(2, MineGenerationBalance.normalizeMonsterCount(2, 0, false));
        assertEquals(5, MineGenerationBalance.normalizeMonsterCount(37, 5, false));
        assertEquals(8, MineGenerationBalance.normalizeMonsterCount(99, 40, false));
    }

    @Test
    void skullCavernUsesAHigherControlledPopulation() {
        assertEquals(3, MineGenerationBalance.normalizeMonsterCount(121, 0, false));
        assertEquals(7, MineGenerationBalance.normalizeMonsterCount(150, 7, false));
        assertEquals(10, MineGenerationBalance.normalizeMonsterCount(200, 40, false));
    }

    @Test
    void monsterMuskDoublesTheClampedPopulationWithinBoostedCaps() {
        assertEquals(4, MineGenerationBalance.normalizeMonsterCount(2, 0, true));
        assertEquals(12, MineGenerationBalance.normalizeMonsterCount(37, 6, true));
        assertEquals(16, MineGenerationBalance.normalizeMonsterCount(99, 40, true));
        assertEquals(6, MineGenerationBalance.normalizeMonsterCount(121, 0, true));
        assertEquals(20, MineGenerationBalance.normalizeMonsterCount(200, 40, true));
    }

    @Test
    void generatorCountsOnlyEntitiesAcceptedByTheLevel() throws Exception {
        Path project = Path.of(System.getProperty("stardewcraft.projectDir", "."));
        String source = Files.readString(project.resolve(
                "src/main/java/com/stardew/craft/mining/MineFloorGenerator.java"))
                .replaceAll("\\s+", "");

        assertTrue(source.contains("privatestaticfinalintGENERATION_VERSION=24;"),
                "the spawn rebalance must invalidate empty floors generated by the old policy");
        assertTrue(source.contains("if(level.addFreshEntity(mob)){spawned++;}"));
        assertFalse(source.contains("level.addFreshEntity(mob);spawned++;"));
    }
}
