package com.stardew.craft.monster;
import net.minecraft.util.RandomSource;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class PepperRexBehaviorTest {
 @Test void sourceTimersKeepPreparationDirectionLockAndResetCadence(){var b=new PepperRexBehavior();var r=RandomSource.create(32);b.initialize(r);assertEquals(PepperRexBehavior.Event.NONE,b.tick(2000,true,true,0,r));assertEquals(PepperRexBehavior.Event.PREPARE,b.tick(1,true,true,0,r));assertEquals(3000,b.remaining());b.tick(499,true,true,1,r);assertEquals(PepperRexBehavior.PREPARE,b.phase());assertEquals(1,b.facing());assertEquals(PepperRexBehavior.Event.FIRST_SHOT,b.tick(1,true,true,1,r));assertEquals(2500,b.remaining());assertEquals(Math.toRadians(25),b.shotAngle(),1e-8);b.tick(69,true,true,3,r);assertEquals(1,b.facing());assertEquals(PepperRexBehavior.Event.SHOT,b.tick(1,true,true,3,r));assertEquals(1,b.facing());var copy=new PepperRexBehavior();copy.load(b.save());assertEquals(b.save(),copy.save());b.tick(2430,true,true,3,r);assertEquals(0,b.phase());assertTrue(b.cooldown()>=1000&&b.cooldown()<2000);}
 @Test void leavingRangeDoesNotInterruptAnExistingVolleyAndLongFrameDoesNotBurstCatchUp(){var b=new PepperRexBehavior();var r=RandomSource.create(7);b.initialize(r);b.tick(2001,true,true,0,r);assertEquals(PepperRexBehavior.Event.FIRST_SHOT,b.tick(500,false,false,2,r));assertEquals(PepperRexBehavior.Event.SHOT,b.tick(600,false,false,1,r));assertEquals(PepperRexBehavior.Event.NONE,b.tick(69,false,false,0,r));assertEquals(PepperRexBehavior.Event.SHOT,b.tick(1,false,false,3,r));assertEquals(2,b.facing());assertEquals(PepperRexBehavior.FIRE,b.phase());}
 @Test void wanderingStaysWithinAdjacentCardinalTurnsAndIsPersisted(){var b=new PepperRexBehavior();var r=RandomSource.create(8);b.initialize(r);boolean walked=false,rested=false;for(int i=0;i<1000;i++){int before=b.facing();b.tick(50,false,false,-1,r);assertNotEquals(2,Math.floorMod(b.facing()-before,4));walked|=b.wander();rested|=!b.wander();assertEquals(0,b.phase());}assertTrue(walked&&rested);var c=new PepperRexBehavior();c.load(b.save());assertEquals(b.save(),c.save());}
}
