package com.stardew.craft.server.performance;

public enum PerformanceTiming {
    SERVER_TICK,
    PLAYER_LOGIN_EVENT,
    CONTENT_SNAPSHOT_BUILD,
    JEI_CATALOG_BUILD,
    FARM_SYNC_CHUNK_LOAD,
    DAILY_SYNC_CHUNK_LOAD,
    DAILY_SETTLEMENT_TOTAL,
    DAILY_SETTLEMENT_TICK,
    DAILY_SETTLEMENT_ATOMIC_ITEM,
    DAILY_SETTLEMENT_LOCK_TO_READY
}
