package com.stardew.craft.server.performance;

public enum PerformanceCounter {
    CONTENT_SYNC_RECIPIENTS,
    CONTENT_SYNC_PACKETS,
    CONTENT_REGISTRY_BYTES,
    JEI_CATALOG_ENTRIES,
    FARM_SYNC_CHUNK_LOADS,
    DAILY_SYNC_CHUNK_LOADS,
    DAILY_SETTLEMENT_TICKS,
    DAILY_SETTLEMENT_ITEMS,
    DAILY_SETTLEMENT_CHUNK_LEASES,
    DAILY_SETTLEMENT_OVERSHOOTS,
    DAILY_SETTLEMENT_RETRIES,
    DAILY_SETTLEMENT_PERMANENT_FAILURES,
    DAILY_SETTLEMENT_PLAYER_BATCHES,
    DAILY_SETTLEMENT_READY_PUBLICATIONS
}
